"use client";

import React, { useState } from "react";
import { motion } from "framer-motion";
import { ShieldCheck, AlertCircle, CheckCircle2, RefreshCw, Link2, ExternalLink, FileText, Lock } from "lucide-react";

export default function SelfCheckSection() {
  const [activeStep, setActiveStep] = useState<"before" | "verifying" | "after">("after");

  return (
    <section id="grounding" className="relative py-24 px-6 z-10">
      <div className="max-w-6xl mx-auto space-y-12">
        {/* Header */}
        <div className="text-center space-y-4 max-w-3xl mx-auto">
          <span className="text-xs font-bold uppercase tracking-widest text-emerald-400 bg-emerald-500/10 px-3.5 py-1.5 rounded-full border border-emerald-500/20">
            Grounding Verification
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
            Self-Checking, Not Hallucinating
          </h2>
          <p className="text-sm sm:text-base text-slate-300 font-medium leading-relaxed">
            Every answer generated by Ask My Docs undergoes automated claim extraction and citation cross-checking against official LangChain documentation before reaching you.
          </p>
        </div>

        {/* Interactive Interactive Stepper Demo Container */}
        <div className="neu-panel p-8 sm:p-10 rounded-3xl border border-white/10 relative overflow-hidden bg-[#1a1d2b]">
          {/* Ambient Glow */}
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />

          {/* Stepper Controls */}
          <div className="flex flex-wrap items-center justify-center gap-3 mb-10 relative z-10">
            <button
              onClick={() => setActiveStep("before")}
              className={`px-5 py-2.5 rounded-xl text-xs font-bold transition-all ${
                activeStep === "before"
                  ? "bg-rose-500/20 text-rose-300 border border-rose-500/30 shadow-md"
                  : "neu-pill text-slate-400 hover:text-slate-200"
              }`}
            >
              1. Unverified Draft Output
            </button>
            <button
              onClick={() => setActiveStep("verifying")}
              className={`px-5 py-2.5 rounded-xl text-xs font-bold transition-all ${
                activeStep === "verifying"
                  ? "bg-amber-500/20 text-amber-300 border border-amber-500/30 shadow-md"
                  : "neu-pill text-slate-400 hover:text-slate-200"
              }`}
            >
              2. LangGraph Grounding Evaluation
            </button>
            <button
              onClick={() => setActiveStep("after")}
              className={`px-5 py-2.5 rounded-xl text-xs font-bold transition-all ${
                activeStep === "after"
                  ? "neu-badge-grounded shadow-md scale-105"
                  : "neu-pill text-slate-400 hover:text-slate-200"
              }`}
            >
              3. Grounded Verified Answer
            </button>
          </div>

          {/* Verification Screen Visual */}
          <div className="max-w-3xl mx-auto space-y-6 relative z-10">
            {/* User Prompt Box */}
            <div className="neu-input-bar p-4 rounded-2xl border border-white/5 flex items-center justify-between">
              <div className="flex items-center gap-3 text-xs font-medium text-slate-300">
                <span className="text-slate-500 font-bold uppercase font-mono">User Query:</span>
                <span>"How do I set up a state graph checkpoint in LangGraph v0.2?"</span>
              </div>
              <span className="text-[10px] font-mono text-blue-400 bg-blue-500/10 px-2.5 py-1 rounded-full border border-blue-500/20 shrink-0">
                LangGraph v0.2
              </span>
            </div>

            {/* Answer State Display */}
            <div className="neu-panel p-6 sm:p-8 rounded-2xl border border-white/10 space-y-6 bg-[#161824]">
              {activeStep === "before" && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-4"
                >
                  <div className="flex items-center justify-between border-b border-rose-500/20 pb-3">
                    <span className="flex items-center gap-2 text-xs font-bold text-rose-400">
                      <AlertCircle className="w-4 h-4" />
                      Unverified Generation (Hallucinated Claims Detected)
                    </span>
                    <span className="text-[10px] font-mono text-rose-400 bg-rose-500/10 px-2 py-0.5 rounded border border-rose-500/20">
                      Grounding Score: 0.38
                    </span>
                  </div>

                  <p className="text-xs sm:text-sm text-slate-300 leading-relaxed font-mono">
                    To add checkpointing, instantiate{" "}
                    <span className="line-through decoration-rose-500 decoration-2 text-rose-400 bg-rose-500/10 px-1 rounded">
                      MemorySaver(sqlite_db="checkpoints.db")
                    </span>{" "}
                    and pass it to{" "}
                    <span className="line-through decoration-rose-500 decoration-2 text-rose-400 bg-rose-500/10 px-1 rounded">
                      builder.compile(checkpointer=MemorySaver)
                    </span>
                    .
                  </p>

                  <div className="p-3 rounded-xl bg-rose-950/30 border border-rose-500/20 text-xs text-rose-300 flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-rose-400 shrink-0" />
                    <span>
                      Flagged: MemorySaver in LangGraph v0.2 takes MemorySaver() without sqlite_db string.
                    </span>
                  </div>
                </motion.div>
              )}

              {activeStep === "verifying" && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.98 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="space-y-4 text-center py-4"
                >
                  <div className="inline-flex items-center gap-3 px-4 py-2 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-300 text-xs font-bold">
                    <RefreshCw className="w-4 h-4 animate-spin text-amber-400" />
                    <span>LangGraph Evaluator Node cross-checking against 4 source chunks...</span>
                  </div>
                  <div className="grid grid-cols-2 gap-3 text-left font-mono text-[11px] max-w-md mx-auto">
                    <div className="neu-input-bar p-3 rounded-xl border border-white/5 text-slate-300">
                      <div className="text-slate-500">Claim 1: MemorySaver()</div>
                      <div className="text-emerald-400 font-bold">MATCHED in doc_2.py</div>
                    </div>
                    <div className="neu-input-bar p-3 rounded-xl border border-white/5 text-slate-300">
                      <div className="text-slate-500">Claim 2: compile(checkpointer=...)</div>
                      <div className="text-emerald-400 font-bold">MATCHED in graph.py</div>
                    </div>
                  </div>
                </motion.div>
              )}

              {activeStep === "after" && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-4"
                >
                  <div className="flex items-center justify-between border-b border-emerald-500/20 pb-3">
                    <span className="flex items-center gap-2 text-xs font-bold text-emerald-400">
                      <CheckCircle2 className="w-4 h-4" />
                      Grounded Answer (100% Citation Backed)
                    </span>
                    <span className="text-[10px] font-mono text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full border border-emerald-500/20">
                      Grounding Score: 0.99
                    </span>
                  </div>

                  <div className="text-xs sm:text-sm text-slate-200 leading-relaxed font-mono space-y-3">
                    <p>
                      In LangGraph v0.2, use <span className="text-blue-400 font-bold">MemorySaver</span> from <span className="text-purple-400 font-bold">langgraph.checkpoint.memory</span>:
                    </p>
                    <pre className="bg-[#12141e] p-3.5 rounded-xl border border-white/5 text-blue-300 text-xs overflow-x-auto">
{`from langgraph.checkpoint.memory import MemorySaver

checkpointer = MemorySaver()
app = builder.compile(checkpointer=checkpointer)`}
                    </pre>
                  </div>

                  {/* Verified Source Citation Chips */}
                  <div className="pt-2 flex flex-wrap items-center gap-2">
                    <span className="text-[10px] text-slate-400 font-bold uppercase">Sources:</span>
                    <a
                      href="https://python.langchain.com/docs/langgraph"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="neu-pill px-3 py-1 rounded-lg text-[11px] font-mono text-blue-400 hover:text-white flex items-center gap-1.5 border border-blue-500/20"
                    >
                      <FileText className="w-3 h-3" />
                      <span>langgraph/checkpoint/memory.py#L42</span>
                      <ExternalLink className="w-2.5 h-2.5 opacity-60" />
                    </a>
                  </div>
                </motion.div>
              )}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
